### ISSUE TITLE
-Werror=misleading-indentation gcc 6.3.0 debian

### ISSUE THREAD

**Issue by krymancer** [girst/base65536#2]
when i try to compile i recive this error.
`gcc -std=c99 -Werror -Wall -Wextra base65536.c main.c -o base65536
main.c: In function ‘main’:
main.c:58:3: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
   if (strcmp (argv [optind], "-") != 0)
   ^~
main.c:60:4: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
    if (op.f == NULL) {
    ^~
cc1: all warnings being treated as errors
Makefile:12: recipe for target 'base65536' failed
make: *** [base65536] Error 1
`
but i just add curly brackets for the if at line 58, thats solve my problem

my gcc version: 
`gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

**Comment by girst** [comment]
thanks! fixed in d59c576b
